# -*- coding: utf-8 -*-
"""Reading/Writing Files.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZhRUoftFfrai23Heq5f6bscrrjAt8Ac_
"""

file = open("D:\\fun.txt", "w")
file.write("I love Python")
file.close()

file = open("D:\\fun.txt", "r")
file.read()

file = open("D:\\fun.txt", "a")
file.write(" 3.1")
file.close()

file = open("D:\\fun.txt", "r")
file.read()

